# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AHRS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AHRS.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nAHRS.proto\"0\n\x04\x41HRS\x12\x0b\n\x03yaw\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\x62\x06proto3')
)




_AHRS = _descriptor.Descriptor(
  name='AHRS',
  full_name='AHRS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaw', full_name='AHRS.yaw', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='AHRS.pitch', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='AHRS.roll', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['AHRS'] = _AHRS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AHRS = _reflection.GeneratedProtocolMessageType('AHRS', (_message.Message,), dict(
  DESCRIPTOR = _AHRS,
  __module__ = 'AHRS_pb2'
  # @@protoc_insertion_point(class_scope:AHRS)
  ))
_sym_db.RegisterMessage(AHRS)


# @@protoc_insertion_point(module_scope)
