# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guiComm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guiComm.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rguiComm.proto\"\xee\x01\n\x07GUIComm\x12\x14\n\x04type\x18\x01 \x01(\x0e\x32\x06.GType\x12\x14\n\x0cjsonMissions\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\x12\x0b\n\x03yaw\x18\x06 \x01(\x02\x12\r\n\x05pitch\x18\x07 \x01(\x02\x12\x0c\n\x04roll\x18\x08 \x01(\x02\x12\x14\n\x0c\x66ireWeapons1\x18\t \x01(\x08\x12\x14\n\x0c\x66ireWeapons2\x18\n \x01(\x08\x12\x14\n\x0c\x66ireWeapons3\x18\x0b \x01(\x08\x12\x14\n\x0c\x66ireWeapons4\x18\x0c \x01(\x08\x12\x14\n\x0c\x66ireWeapons5\x18\r \x01(\x08*\xa7\x02\n\x05GType\x12\x0f\n\x0bSTART_DEBUG\x10\x00\x12\x0e\n\nSTART_AUTO\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x12\n\x0eRESET_MISSIONS\x10\x03\x12\x10\n\x0cMISSION_LIST\x10\x04\x12\x10\n\x0cSKIP_MISSION\x10\x05\x12\x14\n\x10PREVIOUS_MISSION\x10\x06\x12\x16\n\x12\x41\x42SOLUTE_TRANSLATE\x10\x07\x12\x16\n\x12RELATIVE_TRANSLATE\x10\x08\x12\n\n\x06ROTATE\x10\t\x12\x0f\n\x0b\x41\x44\x44_MISSION\x10\n\x12\x12\n\x0eREMOVE_MISSION\x10\x0b\x12\x10\n\x0cSTART_MANUAL\x10\x0c\x12\x0f\n\x0bSTOP_MANUAL\x10\r\x12\x0f\n\x0bUPDATE_PIDS\x10\x0e\x12\x10\n\x0c\x46IRE_WEAPONS\x10\x0f\x62\x06proto3')
)

_GTYPE = _descriptor.EnumDescriptor(
  name='GType',
  full_name='GType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START_DEBUG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_AUTO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET_MISSIONS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_LIST', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SKIP_MISSION', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREVIOUS_MISSION', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABSOLUTE_TRANSLATE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELATIVE_TRANSLATE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTATE', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_MISSION', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE_MISSION', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_MANUAL', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_MANUAL', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_PIDS', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIRE_WEAPONS', index=15, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=259,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_GTYPE)

GType = enum_type_wrapper.EnumTypeWrapper(_GTYPE)
START_DEBUG = 0
START_AUTO = 1
STOP = 2
RESET_MISSIONS = 3
MISSION_LIST = 4
SKIP_MISSION = 5
PREVIOUS_MISSION = 6
ABSOLUTE_TRANSLATE = 7
RELATIVE_TRANSLATE = 8
ROTATE = 9
ADD_MISSION = 10
REMOVE_MISSION = 11
START_MANUAL = 12
STOP_MANUAL = 13
UPDATE_PIDS = 14
FIRE_WEAPONS = 15



_GUICOMM = _descriptor.Descriptor(
  name='GUIComm',
  full_name='GUIComm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GUIComm.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jsonMissions', full_name='GUIComm.jsonMissions', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='GUIComm.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='GUIComm.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='GUIComm.z', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='GUIComm.yaw', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='GUIComm.pitch', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='GUIComm.roll', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fireWeapons1', full_name='GUIComm.fireWeapons1', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fireWeapons2', full_name='GUIComm.fireWeapons2', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fireWeapons3', full_name='GUIComm.fireWeapons3', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fireWeapons4', full_name='GUIComm.fireWeapons4', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fireWeapons5', full_name='GUIComm.fireWeapons5', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=256,
)

_GUICOMM.fields_by_name['type'].enum_type = _GTYPE
DESCRIPTOR.message_types_by_name['GUIComm'] = _GUICOMM
DESCRIPTOR.enum_types_by_name['GType'] = _GTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GUIComm = _reflection.GeneratedProtocolMessageType('GUIComm', (_message.Message,), dict(
  DESCRIPTOR = _GUICOMM,
  __module__ = 'guiComm_pb2'
  # @@protoc_insertion_point(class_scope:GUIComm)
  ))
_sym_db.RegisterMessage(GUIComm)


# @@protoc_insertion_point(module_scope)
