# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydrophones.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydrophones.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11hydrophones.proto\",\n\x0bHydrophones\x12\r\n\x05\x66irst\x18\x01 \x01(\x02\x12\x0e\n\x06second\x18\x02 \x01(\x02\x62\x06proto3')
)




_HYDROPHONES = _descriptor.Descriptor(
  name='Hydrophones',
  full_name='Hydrophones',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='Hydrophones.first', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='Hydrophones.second', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Hydrophones'] = _HYDROPHONES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hydrophones = _reflection.GeneratedProtocolMessageType('Hydrophones', (_message.Message,), dict(
  DESCRIPTOR = _HYDROPHONES,
  __module__ = 'hydrophones_pb2'
  # @@protoc_insertion_point(class_scope:Hydrophones)
  ))
_sym_db.RegisterMessage(Hydrophones)


# @@protoc_insertion_point(module_scope)
