# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leakDetect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='leakDetect.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10leakDetect.proto\"\x1f\n\nLeakDetect\x12\x11\n\tisLeaking\x18\x01 \x01(\x08\x62\x06proto3')
)




_LEAKDETECT = _descriptor.Descriptor(
  name='LeakDetect',
  full_name='LeakDetect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isLeaking', full_name='LeakDetect.isLeaking', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['LeakDetect'] = _LEAKDETECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LeakDetect = _reflection.GeneratedProtocolMessageType('LeakDetect', (_message.Message,), dict(
  DESCRIPTOR = _LEAKDETECT,
  __module__ = 'leakDetect_pb2'
  # @@protoc_insertion_point(class_scope:LeakDetect)
  ))
_sym_db.RegisterMessage(LeakDetect)


# @@protoc_insertion_point(module_scope)
