# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PID_Error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PID_Error.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fPID_Error.proto\"z\n\tPID_Error\x12\x12\n\nroll_error\x18\x01 \x01(\x02\x12\x13\n\x0bpitch_error\x18\x02 \x01(\x02\x12\x11\n\tyaw_error\x18\x03 \x01(\x02\x12\x0f\n\x07x_error\x18\x04 \x01(\x02\x12\x0f\n\x07y_error\x18\x05 \x01(\x02\x12\x0f\n\x07z_error\x18\x06 \x01(\x02\x62\x06proto3')
)




_PID_ERROR = _descriptor.Descriptor(
  name='PID_Error',
  full_name='PID_Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_error', full_name='PID_Error.roll_error', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_error', full_name='PID_Error.pitch_error', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_error', full_name='PID_Error.yaw_error', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_error', full_name='PID_Error.x_error', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_error', full_name='PID_Error.y_error', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_error', full_name='PID_Error.z_error', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['PID_Error'] = _PID_ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PID_Error = _reflection.GeneratedProtocolMessageType('PID_Error', (_message.Message,), dict(
  DESCRIPTOR = _PID_ERROR,
  __module__ = 'PID_Error_pb2'
  # @@protoc_insertion_point(class_scope:PID_Error)
  ))
_sym_db.RegisterMessage(PID_Error)


# @@protoc_insertion_point(module_scope)
