# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pid_errors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pid_errors.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10pid_errors.proto\"\x87\x01\n\nPID_ERRORS\x12\x12\n\nroll_error\x18\x01 \x01(\x02\x12\x13\n\x0bpitch_error\x18\x02 \x01(\x02\x12\x11\n\tyaw_error\x18\x03 \x01(\x02\x12\x13\n\x0bx_pos_error\x18\x04 \x01(\x02\x12\x13\n\x0by_pos_error\x18\x05 \x01(\x02\x12\x13\n\x0bz_pos_error\x18\x06 \x01(\x02\x62\x06proto3')
)




_PID_ERRORS = _descriptor.Descriptor(
  name='PID_ERRORS',
  full_name='PID_ERRORS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_error', full_name='PID_ERRORS.roll_error', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_error', full_name='PID_ERRORS.pitch_error', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_error', full_name='PID_ERRORS.yaw_error', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_pos_error', full_name='PID_ERRORS.x_pos_error', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_pos_error', full_name='PID_ERRORS.y_pos_error', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_pos_error', full_name='PID_ERRORS.z_pos_error', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['PID_ERRORS'] = _PID_ERRORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PID_ERRORS = _reflection.GeneratedProtocolMessageType('PID_ERRORS', (_message.Message,), dict(
  DESCRIPTOR = _PID_ERRORS,
  __module__ = 'pid_errors_pb2'
  # @@protoc_insertion_point(class_scope:PID_ERRORS)
  ))
_sym_db.RegisterMessage(PID_ERRORS)


# @@protoc_insertion_point(module_scope)
