# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pneumatics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pneumatics.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10pneumatics.proto\"\x1b\n\nPneumatics\x12\r\n\x05thing\x18\x01 \x03(\x05\x62\x06proto3')
)




_PNEUMATICS = _descriptor.Descriptor(
  name='Pneumatics',
  full_name='Pneumatics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thing', full_name='Pneumatics.thing', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['Pneumatics'] = _PNEUMATICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pneumatics = _reflection.GeneratedProtocolMessageType('Pneumatics', (_message.Message,), dict(
  DESCRIPTOR = _PNEUMATICS,
  __module__ = 'pneumatics_pb2'
  # @@protoc_insertion_point(class_scope:Pneumatics)
  ))
_sym_db.RegisterMessage(Pneumatics)


# @@protoc_insertion_point(module_scope)
