# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thrusters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='thrusters.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fthrusters.proto\"\xab\x01\n\tThrusters\x12\x12\n\nthruster_1\x18\x01 \x01(\x05\x12\x12\n\nthruster_2\x18\x02 \x01(\x05\x12\x12\n\nthruster_3\x18\x03 \x01(\x05\x12\x12\n\nthruster_4\x18\x04 \x01(\x05\x12\x12\n\nthruster_5\x18\x05 \x01(\x05\x12\x12\n\nthruster_6\x18\x06 \x01(\x05\x12\x12\n\nthruster_7\x18\x07 \x01(\x05\x12\x12\n\nthruster_8\x18\x08 \x01(\x05\x62\x06proto3')
)




_THRUSTERS = _descriptor.Descriptor(
  name='Thrusters',
  full_name='Thrusters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thruster_1', full_name='Thrusters.thruster_1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_2', full_name='Thrusters.thruster_2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_3', full_name='Thrusters.thruster_3', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_4', full_name='Thrusters.thruster_4', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_5', full_name='Thrusters.thruster_5', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_6', full_name='Thrusters.thruster_6', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_7', full_name='Thrusters.thruster_7', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thruster_8', full_name='Thrusters.thruster_8', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['Thrusters'] = _THRUSTERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Thrusters = _reflection.GeneratedProtocolMessageType('Thrusters', (_message.Message,), dict(
  DESCRIPTOR = _THRUSTERS,
  __module__ = 'thrusters_pb2'
  # @@protoc_insertion_point(class_scope:Thrusters)
  ))
_sym_db.RegisterMessage(Thrusters)


# @@protoc_insertion_point(module_scope)
